In [61]:
import kagglehub
import pandas as pd
import os

import sqlite3

In [62]:
# Download latest version
path = kagglehub.dataset_download("dhrubangtalukdar/store-item-demand-forecasting-dataset")

print("Path to dataset files:", path)

Path to dataset files: /Users/emmanuelahadzi/.cache/kagglehub/datasets/dhrubangtalukdar/store-item-demand-forecasting-dataset/versions/1

In [63]:
# Show all files inside the folder
print("\nFiles in dataset folder:")
print(os.listdir(path))

Files in dataset folder:
['retail_sales.csv']

In [64]:
# Load the CSV file
csv_file = os.path.join(path, 'retail_sales.csv')

# Read dataset into pandas dataframe
df = pd.read_csv(csv_file)
df.head(11)

          date store_id item_id  sales  price  promo  weekday  month
0   2019-01-01  store_1  item_1     41  21.30      0        1      1
1   2019-01-02  store_1  item_1     53  21.30      0        2      1
2   2019-01-03  store_1  item_1     39  21.30      0        3      1
3   2019-01-04  store_1  item_1     35  21.30      0        4      1
4   2019-01-05  store_1  item_1     51  17.04      1        5      1
5   2019-01-06  store_1  item_1     38  21.30      0        6      1
6   2019-01-07  store_1  item_1     45  21.30      0        0      1
7   2019-01-08  store_1  item_1     48  21.30      0        1      1
8   2019-01-09  store_1  item_1     50  21.30      0        2      1
9   2019-01-10  store_1  item_1     44  21.30      0        3      1
10  2019-01-11  store_1  item_1     38  21.30      0        4      1

In [65]:
# Print dataset information
print("\nDataset Information:")
df.info()

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4565000 entries, 0 to 4564999
Data columns (total 8 columns):
 #   Column    Dtype
---  ------    -----
 0   date      object
 1   store_id  object
 2   item_id   object
 3   sales     int64
 4   price     float64
 5   promo     int64
 6   weekday   int64
 7   month     int64
dtypes: float64(1), int64(4), object(3)
memory usage: 278.6+ MB

In [73]:
# Print dataset structure
print("\nDataset structure:")
df.describe()

Dataset structure:

              sales         price         promo       weekday         month
count  4.565000e+06  4.565000e+06  4.565000e+06  4.565000e+06  4.565000e+06
mean   2.926466e+01  5.399323e+01  9.999869e-02  3.001643e+00  6.523549e+00
std    1.500996e+01  2.578461e+01  2.999983e-01  1.999315e+00  3.448534e+00
min    0.000000e+00  8.020000e+00  0.000000e+00  0.000000e+00  1.000000e+00
25%    1.800000e+01  3.197000e+01  0.000000e+00  1.000000e+00  4.000000e+00
50%    2.700000e+01  5.352000e+01  0.000000e+00  3.000000e+00  7.000000e+00
75%    3.800000e+01  7.536000e+01  0.000000e+00  5.000000e+00  1.000000e+01
max    1.390000e+02  9.999000e+01  1.000000e+00  6.000000e+00  1.200000e+01

In [70]:
# SQL- style ingestion 
conn = sqlite3.connect("retail_sales.db")

# Store dataframe into SQL table
df.to_sql(
    "sales_data",
    conn,
    if_exists="replace",
    index=False)

print('Dataset stored successfully')

Dataset stored successfully

In [68]:
# SQL Querying 
query = """
SELECT store_id AS store,
       item_id AS item,
       AVG(sales) AS avg_sales
FROM sales_data
GROUP BY store_id, item_id
"""
# Execute query
sales_summary = pd.read_sql(query, conn)

# Print result
print(sales_summary.head())

     store     item  avg_sales
0  store_1   item_1  44.780942
1  store_1  item_10  22.625958
2  store_1  item_11  24.568456
3  store_1  item_12  20.680175
4  store_1  item_13  39.995619

In [85]:
# DATA PREPROCESSING

In [81]:
# Missing Values
print(df.isnull().sum())

date        0
store_id    0
item_id     0
sales       0
price       0
promo       0
weekday     0
month       0
dtype: int64

In [89]:
# Duplicate Records 
print(df.duplicated().sum())

0

In [79]:
# Outlier Detection

In [80]:
# Feature Engineering

In [ ]:
# Data Visualisation